[package]
name = "snapcd"
version = "0.1.0"
authors = ["5225225 <5225225@mailbox.org>"]
edition = "2018"

[dependencies]
serde_cbor = "0.11.2"
serde = { version = "1.0.130", features = ["derive"] }
structopt = "0.3.23"
rusqlite = { version = "0.25.3", features = ["trace"] }
bitvec = "0.22.3"
globset = "0.4.8"
dirs = "4.0.0"
either = "1.6.1"
colored = "2.0.0"
gearhash = "0.1.3"
static_assertions = "1.1.0"
serde_bytes = "0.11.5"
blake3 = "1.0.0"
thiserror = "1.0.29"
clap = "2.33.3"
diff = "0.1.12"
anyhow = "1.0.44"
difference = "2.0.0"
patch = "0.5.0"
itertools = "0.10.1"
beef = "0.5.1"
rand = "0.8.4"
aes-gcm-siv = "0.10.3"
enum_dispatch = "0.3.7"
pretty-hex = "0.2.1"
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
tracing-log = "0.1.2"
ureq = "2.2.0"
libsnapcd = { path = "../libsnapcd" }
cap-std = "0.19.1"

[dev-dependencies]
criterion = "0.3.5"
rand = "0.8.4"
rand_chacha = "0.3.1"
fastrand = "1.5.0"
proptest = "1.0.0"
proptest-derive = "0.3.0"
assert_fs = "1.0.5"
assert_cmd = "2.0.1"
indoc = "1.0.3"
tempfile = "3.2.0"
cap-tempfile = "0.19.1"

[[bench]]
name = "my_benchmark"
harness = false
