[package]
name = "snapcd"
version = "0.1.0"
authors = ["5225225 <5225225@mailbox.org>"]
edition = "2018"

[dependencies]
serde_cbor = "0.11.1"
serde = { version = "1.0.123", features = ["derive"] }
structopt = "0.3.21"
rusqlite = { version = "0.24.2", features = ["trace"] }
bitvec = "0.21.0"
hex = "0.4.2"
log = "0.4.14"
globset = "0.4.6"
dirs = "3.0.1"
either = "1.6.1"
colored = "2.0.0"
gearhash = "0.1.3"
static_assertions = "1.1.0"
serde_bytes = "0.11.5"
blake3 = "0.3.7"
thiserror = "1.0.24"
clap = "2.33.3"
diff = "0.1.12"
anyhow = "1.0.38"

simplelog = { version = "0.9.0", optional = true }
difference = "2.0.0"
patch = "0.5.0"
itertools = "0.10.0"
beef = "0.5.0"
rand = "0.8.3"
aes-gcm-siv = "0.9.0"
enum_dispatch = "0.3.5"
pretty-hex = "0.2.1"
assert_fs = "1.0.1"
assert_cmd = "1.0.3"
indoc = "1.0.3"

[features]
default = ["logging"]
logging = ["simplelog"]

[dev-dependencies]
criterion = "0.3.4"
rand = "0.8.3"
rand_chacha = "0.3.0"
fastrand = "1.4.0"
tempfile = "3.2.0"
proptest = "1.0.0"
proptest-derive = "0.3.0"

[[bench]]
name = "my_benchmark"
harness = false
