[package]
name = "snapcd"
version = "0.1.0"
authors = ["5225225 <5225225@mailbox.org>"]
edition = "2018"

[dependencies]
serde_cbor = "0.11.1"
serde = { version = "1.0.125", features = ["derive"] }
structopt = "0.3.21"
rusqlite = { version = "0.25.1", features = ["trace"] }
bitvec = "0.22.3"
globset = "0.4.6"
dirs = "3.0.2"
either = "1.6.1"
colored = "2.0.0"
gearhash = "0.1.3"
static_assertions = "1.1.0"
serde_bytes = "0.11.5"
blake3 = "0.3.7"
thiserror = "1.0.24"
clap = "2.33.3"
diff = "0.1.12"
anyhow = "1.0.40"
difference = "2.0.0"
patch = "0.5.0"
itertools = "0.10.0"
beef = "0.5.0"
rand = "0.8.3"
aes-gcm-siv = "0.10.0"
enum_dispatch = "0.3.6"
pretty-hex = "0.2.1"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
tracing-log = "0.1.2"
ureq = "2.1.1"
cap-std = { git = "https://github.com/bytecodealliance/cap-std", branch = "sunfishcode/ambient-authority" }
libsnapcd = { path = "../libsnapcd" }

[dev-dependencies]
criterion = "0.3.4"
rand = "0.8.3"
rand_chacha = "0.3.0"
fastrand = "1.4.1"
cap-tempfile = { git = "https://github.com/bytecodealliance/cap-std", branch = "sunfishcode/ambient-authority" }
proptest = "1.0.0"
proptest-derive = "0.3.0"
assert_fs = "1.0.2"
assert_cmd = "1.0.3"
indoc = "1.0.3"
tempfile = "3.2.0"

[[bench]]
name = "my_benchmark"
harness = false
